# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'swim_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1336, 761)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(46, 52, 54);\n"
"")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(560, 10, 71, 61))
        self.lcdNumber.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(760, 10, 101, 61))
        self.lcdNumber_2.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_2.setDigitCount(3)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(660, 10, 71, 61))
        self.lcdNumber_3.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_3.setDigitCount(2)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_76 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_76.setGeometry(QtCore.QRect(70, 530, 51, 51))
        self.lcdNumber_76.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_76.setDigitCount(2)
        self.lcdNumber_76.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_76.setProperty("value", 7.0)
        self.lcdNumber_76.setObjectName("lcdNumber_76")
        self.lcdNumber_77 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_77.setGeometry(QtCore.QRect(70, 390, 51, 51))
        self.lcdNumber_77.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_77.setDigitCount(2)
        self.lcdNumber_77.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_77.setProperty("value", 5.0)
        self.lcdNumber_77.setObjectName("lcdNumber_77")
        self.lcdNumber_78 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_78.setGeometry(QtCore.QRect(70, 600, 51, 51))
        self.lcdNumber_78.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_78.setDigitCount(2)
        self.lcdNumber_78.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_78.setProperty("value", 8.0)
        self.lcdNumber_78.setObjectName("lcdNumber_78")
        self.lcdNumber_79 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_79.setGeometry(QtCore.QRect(70, 110, 51, 51))
        self.lcdNumber_79.setStyleSheet("color: rgb(204, 0, 0);\n"
"color: rgb(245, 121, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_79.setDigitCount(2)
        self.lcdNumber_79.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_79.setProperty("value", 1.0)
        self.lcdNumber_79.setObjectName("lcdNumber_79")
        self.lcdNumber_80 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_80.setGeometry(QtCore.QRect(70, 180, 51, 51))
        self.lcdNumber_80.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_80.setDigitCount(2)
        self.lcdNumber_80.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_80.setProperty("value", 2.0)
        self.lcdNumber_80.setObjectName("lcdNumber_80")
        self.lcdNumber_81 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_81.setGeometry(QtCore.QRect(70, 320, 51, 51))
        self.lcdNumber_81.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_81.setDigitCount(2)
        self.lcdNumber_81.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_81.setProperty("value", 4.0)
        self.lcdNumber_81.setObjectName("lcdNumber_81")
        self.lcdNumber_82 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_82.setGeometry(QtCore.QRect(70, 250, 51, 51))
        self.lcdNumber_82.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(204, 0, 0);")
        self.lcdNumber_82.setDigitCount(2)
        self.lcdNumber_82.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_82.setProperty("value", 3.0)
        self.lcdNumber_82.setObjectName("lcdNumber_82")
        self.lcdNumber_83 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_83.setGeometry(QtCore.QRect(70, 460, 51, 51))
        self.lcdNumber_83.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_83.setDigitCount(2)
        self.lcdNumber_83.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_83.setProperty("value", 6.0)
        self.lcdNumber_83.setObjectName("lcdNumber_83")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(690, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(950, 70, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1160, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_18.setGeometry(QtCore.QRect(1000, 110, 51, 51))
        self.lcdNumber_18.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_18.setDigitCount(2)
        self.lcdNumber_18.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_16.setGeometry(QtCore.QRect(940, 110, 51, 51))
        self.lcdNumber_16.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_16.setDigitCount(2)
        self.lcdNumber_16.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_19.setGeometry(QtCore.QRect(1060, 110, 71, 51))
        self.lcdNumber_19.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_19.setDigitCount(3)
        self.lcdNumber_19.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_20.setGeometry(QtCore.QRect(1000, 180, 51, 51))
        self.lcdNumber_20.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_20.setDigitCount(2)
        self.lcdNumber_20.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.lcdNumber_21 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_21.setGeometry(QtCore.QRect(940, 180, 51, 51))
        self.lcdNumber_21.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_21.setDigitCount(2)
        self.lcdNumber_21.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.lcdNumber_22 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_22.setGeometry(QtCore.QRect(1060, 180, 71, 51))
        self.lcdNumber_22.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_22.setDigitCount(3)
        self.lcdNumber_22.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.lcdNumber_72 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_72.setGeometry(QtCore.QRect(430, 110, 171, 51))
        self.lcdNumber_72.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_72.setDigitCount(7)
        self.lcdNumber_72.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_72.setObjectName("lcdNumber_72")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(440, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 120, 51, 521))
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("refresh-button-icon-56615.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lcdNumber_73 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_73.setGeometry(QtCore.QRect(430, 180, 171, 51))
        self.lcdNumber_73.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_73.setDigitCount(7)
        self.lcdNumber_73.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_73.setObjectName("lcdNumber_73")
        self.lcdNumber_75 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_75.setGeometry(QtCore.QRect(430, 320, 171, 51))
        self.lcdNumber_75.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_75.setDigitCount(7)
        self.lcdNumber_75.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_75.setObjectName("lcdNumber_75")
        self.lcdNumber_74 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_74.setGeometry(QtCore.QRect(430, 250, 171, 51))
        self.lcdNumber_74.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_74.setDigitCount(7)
        self.lcdNumber_74.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_74.setObjectName("lcdNumber_74")
        self.lcdNumber_84 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_84.setGeometry(QtCore.QRect(430, 390, 171, 51))
        self.lcdNumber_84.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_84.setDigitCount(7)
        self.lcdNumber_84.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_84.setObjectName("lcdNumber_84")
        self.lcdNumber_96 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_96.setGeometry(QtCore.QRect(430, 460, 171, 51))
        self.lcdNumber_96.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_96.setDigitCount(7)
        self.lcdNumber_96.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_96.setObjectName("lcdNumber_96")
        self.lcdNumber_99 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_99.setGeometry(QtCore.QRect(430, 530, 171, 51))
        self.lcdNumber_99.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_99.setDigitCount(7)
        self.lcdNumber_99.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_99.setObjectName("lcdNumber_99")
        self.lcdNumber_88 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_88.setGeometry(QtCore.QRect(430, 600, 171, 51))
        self.lcdNumber_88.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_88.setDigitCount(7)
        self.lcdNumber_88.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_88.setObjectName("lcdNumber_88")
        self.lcdNumber_23 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_23.setGeometry(QtCore.QRect(1000, 250, 51, 51))
        self.lcdNumber_23.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_23.setDigitCount(2)
        self.lcdNumber_23.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.lcdNumber_24 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_24.setGeometry(QtCore.QRect(1060, 250, 71, 51))
        self.lcdNumber_24.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_24.setDigitCount(3)
        self.lcdNumber_24.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_24.setObjectName("lcdNumber_24")
        self.lcdNumber_25 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_25.setGeometry(QtCore.QRect(940, 250, 51, 51))
        self.lcdNumber_25.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_25.setDigitCount(2)
        self.lcdNumber_25.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_25.setObjectName("lcdNumber_25")
        self.lcdNumber_26 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_26.setGeometry(QtCore.QRect(1000, 320, 51, 51))
        self.lcdNumber_26.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_26.setDigitCount(2)
        self.lcdNumber_26.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_26.setObjectName("lcdNumber_26")
        self.lcdNumber_27 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_27.setGeometry(QtCore.QRect(1060, 320, 71, 51))
        self.lcdNumber_27.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_27.setDigitCount(3)
        self.lcdNumber_27.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_27.setObjectName("lcdNumber_27")
        self.lcdNumber_28 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_28.setGeometry(QtCore.QRect(940, 320, 51, 51))
        self.lcdNumber_28.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_28.setDigitCount(2)
        self.lcdNumber_28.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_28.setObjectName("lcdNumber_28")
        self.lcdNumber_29 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_29.setGeometry(QtCore.QRect(1000, 390, 51, 51))
        self.lcdNumber_29.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_29.setDigitCount(2)
        self.lcdNumber_29.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_29.setObjectName("lcdNumber_29")
        self.lcdNumber_30 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_30.setGeometry(QtCore.QRect(1060, 390, 71, 51))
        self.lcdNumber_30.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_30.setDigitCount(3)
        self.lcdNumber_30.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_30.setObjectName("lcdNumber_30")
        self.lcdNumber_31 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_31.setGeometry(QtCore.QRect(940, 390, 51, 51))
        self.lcdNumber_31.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_31.setDigitCount(2)
        self.lcdNumber_31.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_31.setObjectName("lcdNumber_31")
        self.lcdNumber_32 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_32.setGeometry(QtCore.QRect(1000, 460, 51, 51))
        self.lcdNumber_32.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_32.setDigitCount(2)
        self.lcdNumber_32.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_32.setObjectName("lcdNumber_32")
        self.lcdNumber_33 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_33.setGeometry(QtCore.QRect(1060, 460, 71, 51))
        self.lcdNumber_33.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_33.setDigitCount(3)
        self.lcdNumber_33.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_33.setObjectName("lcdNumber_33")
        self.lcdNumber_34 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_34.setGeometry(QtCore.QRect(940, 460, 51, 51))
        self.lcdNumber_34.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_34.setDigitCount(2)
        self.lcdNumber_34.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_34.setObjectName("lcdNumber_34")
        self.lcdNumber_35 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_35.setGeometry(QtCore.QRect(1000, 530, 51, 51))
        self.lcdNumber_35.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_35.setDigitCount(2)
        self.lcdNumber_35.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_35.setObjectName("lcdNumber_35")
        self.lcdNumber_36 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_36.setGeometry(QtCore.QRect(1060, 530, 71, 51))
        self.lcdNumber_36.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_36.setDigitCount(3)
        self.lcdNumber_36.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_36.setObjectName("lcdNumber_36")
        self.lcdNumber_37 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_37.setGeometry(QtCore.QRect(940, 530, 51, 51))
        self.lcdNumber_37.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_37.setDigitCount(2)
        self.lcdNumber_37.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_37.setObjectName("lcdNumber_37")
        self.lcdNumber_38 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_38.setGeometry(QtCore.QRect(1000, 600, 51, 51))
        self.lcdNumber_38.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_38.setDigitCount(2)
        self.lcdNumber_38.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_38.setObjectName("lcdNumber_38")
        self.lcdNumber_39 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_39.setGeometry(QtCore.QRect(1060, 600, 71, 51))
        self.lcdNumber_39.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_39.setDigitCount(3)
        self.lcdNumber_39.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_39.setObjectName("lcdNumber_39")
        self.lcdNumber_40 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_40.setGeometry(QtCore.QRect(940, 600, 51, 51))
        self.lcdNumber_40.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_40.setDigitCount(2)
        self.lcdNumber_40.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_40.setObjectName("lcdNumber_40")
        self.lcdNumber_41 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_41.setGeometry(QtCore.QRect(730, 390, 51, 51))
        self.lcdNumber_41.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_41.setDigitCount(2)
        self.lcdNumber_41.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_41.setObjectName("lcdNumber_41")
        self.lcdNumber_42 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_42.setGeometry(QtCore.QRect(730, 250, 51, 51))
        self.lcdNumber_42.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_42.setDigitCount(2)
        self.lcdNumber_42.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_42.setObjectName("lcdNumber_42")
        self.lcdNumber_43 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_43.setGeometry(QtCore.QRect(670, 460, 51, 51))
        self.lcdNumber_43.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_43.setDigitCount(2)
        self.lcdNumber_43.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_43.setObjectName("lcdNumber_43")
        self.lcdNumber_44 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_44.setGeometry(QtCore.QRect(730, 600, 51, 51))
        self.lcdNumber_44.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_44.setDigitCount(2)
        self.lcdNumber_44.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_44.setObjectName("lcdNumber_44")
        self.lcdNumber_45 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_45.setGeometry(QtCore.QRect(730, 180, 51, 51))
        self.lcdNumber_45.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_45.setDigitCount(2)
        self.lcdNumber_45.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_45.setObjectName("lcdNumber_45")
        self.lcdNumber_46 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_46.setGeometry(QtCore.QRect(730, 460, 51, 51))
        self.lcdNumber_46.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_46.setDigitCount(2)
        self.lcdNumber_46.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_46.setObjectName("lcdNumber_46")
        self.lcdNumber_47 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_47.setGeometry(QtCore.QRect(670, 600, 51, 51))
        self.lcdNumber_47.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_47.setDigitCount(2)
        self.lcdNumber_47.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_47.setObjectName("lcdNumber_47")
        self.lcdNumber_48 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_48.setGeometry(QtCore.QRect(670, 110, 51, 51))
        self.lcdNumber_48.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_48.setDigitCount(2)
        self.lcdNumber_48.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_48.setObjectName("lcdNumber_48")
        self.lcdNumber_49 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_49.setGeometry(QtCore.QRect(670, 320, 51, 51))
        self.lcdNumber_49.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_49.setDigitCount(2)
        self.lcdNumber_49.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_49.setObjectName("lcdNumber_49")
        self.lcdNumber_50 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_50.setGeometry(QtCore.QRect(670, 180, 51, 51))
        self.lcdNumber_50.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_50.setDigitCount(2)
        self.lcdNumber_50.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_50.setObjectName("lcdNumber_50")
        self.lcdNumber_51 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_51.setGeometry(QtCore.QRect(790, 600, 71, 51))
        self.lcdNumber_51.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_51.setDigitCount(3)
        self.lcdNumber_51.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_51.setObjectName("lcdNumber_51")
        self.lcdNumber_52 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_52.setGeometry(QtCore.QRect(790, 180, 71, 51))
        self.lcdNumber_52.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_52.setDigitCount(3)
        self.lcdNumber_52.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_52.setObjectName("lcdNumber_52")
        self.lcdNumber_53 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_53.setGeometry(QtCore.QRect(730, 320, 51, 51))
        self.lcdNumber_53.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_53.setDigitCount(2)
        self.lcdNumber_53.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_53.setObjectName("lcdNumber_53")
        self.lcdNumber_54 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_54.setGeometry(QtCore.QRect(790, 530, 71, 51))
        self.lcdNumber_54.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_54.setDigitCount(3)
        self.lcdNumber_54.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_54.setObjectName("lcdNumber_54")
        self.lcdNumber_55 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_55.setGeometry(QtCore.QRect(730, 110, 51, 51))
        self.lcdNumber_55.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_55.setDigitCount(2)
        self.lcdNumber_55.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_55.setObjectName("lcdNumber_55")
        self.lcdNumber_56 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_56.setGeometry(QtCore.QRect(790, 460, 71, 51))
        self.lcdNumber_56.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_56.setDigitCount(3)
        self.lcdNumber_56.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_56.setObjectName("lcdNumber_56")
        self.lcdNumber_57 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_57.setGeometry(QtCore.QRect(790, 110, 71, 51))
        self.lcdNumber_57.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_57.setDigitCount(3)
        self.lcdNumber_57.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_57.setObjectName("lcdNumber_57")
        self.lcdNumber_58 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_58.setGeometry(QtCore.QRect(670, 530, 51, 51))
        self.lcdNumber_58.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_58.setDigitCount(2)
        self.lcdNumber_58.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_58.setObjectName("lcdNumber_58")
        self.lcdNumber_66 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_66.setGeometry(QtCore.QRect(790, 250, 71, 51))
        self.lcdNumber_66.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_66.setDigitCount(3)
        self.lcdNumber_66.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_66.setObjectName("lcdNumber_66")
        self.lcdNumber_67 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_67.setGeometry(QtCore.QRect(790, 320, 71, 51))
        self.lcdNumber_67.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_67.setDigitCount(3)
        self.lcdNumber_67.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_67.setObjectName("lcdNumber_67")
        self.lcdNumber_68 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_68.setGeometry(QtCore.QRect(730, 530, 51, 51))
        self.lcdNumber_68.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_68.setDigitCount(2)
        self.lcdNumber_68.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_68.setObjectName("lcdNumber_68")
        self.lcdNumber_69 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_69.setGeometry(QtCore.QRect(790, 390, 71, 51))
        self.lcdNumber_69.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_69.setDigitCount(3)
        self.lcdNumber_69.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_69.setObjectName("lcdNumber_69")
        self.lcdNumber_70 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_70.setGeometry(QtCore.QRect(670, 250, 51, 51))
        self.lcdNumber_70.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_70.setDigitCount(2)
        self.lcdNumber_70.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_70.setObjectName("lcdNumber_70")
        self.lcdNumber_71 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_71.setGeometry(QtCore.QRect(670, 390, 51, 51))
        self.lcdNumber_71.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_71.setDigitCount(2)
        self.lcdNumber_71.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_71.setObjectName("lcdNumber_71")
        self.lcdNumber_103 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_103.setGeometry(QtCore.QRect(1190, 110, 51, 51))
        self.lcdNumber_103.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_103.setDigitCount(2)
        self.lcdNumber_103.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_103.setProperty("value", 0.0)
        self.lcdNumber_103.setProperty("intValue", 0)
        self.lcdNumber_103.setObjectName("lcdNumber_103")
        self.lcdNumber_105 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_105.setGeometry(QtCore.QRect(1190, 180, 51, 51))
        self.lcdNumber_105.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_105.setDigitCount(2)
        self.lcdNumber_105.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_105.setProperty("value", 0.0)
        self.lcdNumber_105.setProperty("intValue", 0)
        self.lcdNumber_105.setObjectName("lcdNumber_105")
        self.lcdNumber_106 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_106.setGeometry(QtCore.QRect(1190, 250, 51, 51))
        self.lcdNumber_106.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(204, 0, 0);")
        self.lcdNumber_106.setDigitCount(2)
        self.lcdNumber_106.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_106.setProperty("value", 0.0)
        self.lcdNumber_106.setProperty("intValue", 0)
        self.lcdNumber_106.setObjectName("lcdNumber_106")
        self.lcdNumber_107 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_107.setGeometry(QtCore.QRect(1190, 320, 51, 51))
        self.lcdNumber_107.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_107.setDigitCount(2)
        self.lcdNumber_107.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_107.setProperty("value", 0.0)
        self.lcdNumber_107.setProperty("intValue", 0)
        self.lcdNumber_107.setObjectName("lcdNumber_107")
        self.lcdNumber_108 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_108.setGeometry(QtCore.QRect(1190, 390, 51, 51))
        self.lcdNumber_108.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_108.setDigitCount(2)
        self.lcdNumber_108.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_108.setProperty("value", 0.0)
        self.lcdNumber_108.setProperty("intValue", 0)
        self.lcdNumber_108.setObjectName("lcdNumber_108")
        self.lcdNumber_109 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_109.setGeometry(QtCore.QRect(1190, 460, 51, 51))
        self.lcdNumber_109.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_109.setDigitCount(2)
        self.lcdNumber_109.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_109.setProperty("value", 0.0)
        self.lcdNumber_109.setProperty("intValue", 0)
        self.lcdNumber_109.setObjectName("lcdNumber_109")
        self.lcdNumber_110 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_110.setGeometry(QtCore.QRect(1190, 530, 51, 51))
        self.lcdNumber_110.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_110.setDigitCount(2)
        self.lcdNumber_110.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_110.setProperty("value", 0.0)
        self.lcdNumber_110.setProperty("intValue", 0)
        self.lcdNumber_110.setObjectName("lcdNumber_110")
        self.lcdNumber_111 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_111.setGeometry(QtCore.QRect(1190, 600, 51, 51))
        self.lcdNumber_111.setStyleSheet("color: rgb(204, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lcdNumber_111.setDigitCount(2)
        self.lcdNumber_111.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_111.setProperty("value", 0.0)
        self.lcdNumber_111.setProperty("intValue", 0)
        self.lcdNumber_111.setObjectName("lcdNumber_111")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(46, 52, 54);\n"
"")
        self.lineEdit_9.setClearButtonEnabled(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1030, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1150, 20, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1230, 20, 41, 41))
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 120, 171, 31))
        self.comboBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(46, 52, 54);\n"
"font: 75 20pt \"Ubuntu Condensed\";\n"
"background-color: rgb(46, 52, 54);")
        self.comboBox.setEditable(True)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtCurrent)
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 190, 171, 31))
        self.comboBox_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(46, 52, 54);\n"
"font: 75 20pt \"Ubuntu Condensed\";\n"
"background-color: rgb(46, 52, 54);")
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(160, 260, 171, 31))
        self.comboBox_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(46, 52, 54);\n"
"font: 75 20pt \"Ubuntu Condensed\";\n"
"background-color: rgb(46, 52, 54);")
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(160, 330, 171, 31))
        self.comboBox_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(46, 52, 54);\n"
"font: 75 20pt \"Ubuntu Condensed\";\n"
"background-color: rgb(46, 52, 54);")
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(160, 400, 171, 31))
        self.comboBox_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(46, 52, 54);\n"
"font: 75 20pt \"Ubuntu Condensed\";\n"
"background-color: rgb(46, 52, 54);")
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(160, 470, 171, 31))
        self.comboBox_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(46, 52, 54);\n"
"font: 75 20pt \"Ubuntu Condensed\";\n"
"background-color: rgb(46, 52, 54);")
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_7.setGeometry(QtCore.QRect(160, 540, 171, 31))
        self.comboBox_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(46, 52, 54);\n"
"font: 75 20pt \"Ubuntu Condensed\";\n"
"background-color: rgb(46, 52, 54);")
        self.comboBox_7.setEditable(True)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_8.setGeometry(QtCore.QRect(160, 610, 171, 31))
        self.comboBox_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(46, 52, 54);\n"
"font: 75 20pt \"Ubuntu Condensed\";\n"
"background-color: rgb(46, 52, 54);")
        self.comboBox_8.setEditable(True)
        self.comboBox_8.setObjectName("comboBox_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1336, 22))
        self.menubar.setStyleSheet("color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("")
        self.menuFile.setObjectName("menuFile")
        self.menuSegment = QtWidgets.QMenu(self.menubar)
        self.menuSegment.setObjectName("menuSegment")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuset_COM_port = QtWidgets.QMenu(self.menuSettings)
        self.menuset_COM_port.setObjectName("menuset_COM_port")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action50m = QtWidgets.QAction(MainWindow)
        self.action50m.setCheckable(True)
        self.action50m.setChecked(True)
        self.action50m.setObjectName("action50m")
        self.action100m_freestyle = QtWidgets.QAction(MainWindow)
        self.action100m_freestyle.setCheckable(True)
        self.action100m_freestyle.setObjectName("action100m_freestyle")
        self.action100m_backstroke = QtWidgets.QAction(MainWindow)
        self.action100m_backstroke.setCheckable(True)
        self.action100m_backstroke.setObjectName("action100m_backstroke")
        self.action100m_butterfly = QtWidgets.QAction(MainWindow)
        self.action100m_butterfly.setCheckable(True)
        self.action100m_butterfly.setObjectName("action100m_butterfly")
        self.action200m_freestyle = QtWidgets.QAction(MainWindow)
        self.action200m_freestyle.setCheckable(True)
        self.action200m_freestyle.setObjectName("action200m_freestyle")
        self.action200m_backstroke = QtWidgets.QAction(MainWindow)
        self.action200m_backstroke.setCheckable(True)
        self.action200m_backstroke.setObjectName("action200m_backstroke")
        self.action200m_butterfly = QtWidgets.QAction(MainWindow)
        self.action200m_butterfly.setCheckable(True)
        self.action200m_butterfly.setObjectName("action200m_butterfly")
        self.actionavailable_ports = QtWidgets.QAction(MainWindow)
        self.actionavailable_ports.setCheckable(True)
        self.actionavailable_ports.setEnabled(True)
        self.actionavailable_ports.setObjectName("actionavailable_ports")
        self.actionavailable_ports_2 = QtWidgets.QAction(MainWindow)
        self.actionavailable_ports_2.setCheckable(True)
        self.actionavailable_ports_2.setObjectName("actionavailable_ports_2")
        self.actionavailable_ports_3 = QtWidgets.QAction(MainWindow)
        self.actionavailable_ports_3.setCheckable(True)
        self.actionavailable_ports_3.setObjectName("actionavailable_ports_3")
        self.actionavailable_ports_4 = QtWidgets.QAction(MainWindow)
        self.actionavailable_ports_4.setCheckable(True)
        self.actionavailable_ports_4.setObjectName("actionavailable_ports_4")
        self.actionOpen_Database = QtWidgets.QAction(MainWindow)
        self.actionOpen_Database.setObjectName("actionOpen_Database")
        self.actionImprovement_Curve = QtWidgets.QAction(MainWindow)
        self.actionImprovement_Curve.setObjectName("actionImprovement_Curve")
        self.menuSegment.addSeparator()
        self.menuSegment.addAction(self.action50m)
        self.menuSegment.addAction(self.action100m_freestyle)
        self.menuSegment.addAction(self.action100m_backstroke)
        self.menuSegment.addAction(self.action100m_butterfly)
        self.menuSegment.addAction(self.action200m_freestyle)
        self.menuSegment.addAction(self.action200m_backstroke)
        self.menuSegment.addAction(self.action200m_butterfly)
        self.menuSegment.addSeparator()
        self.menuDatabase.addAction(self.actionOpen_Database)
        self.menuDatabase.addAction(self.actionImprovement_Curve)
        self.menuset_COM_port.addAction(self.actionavailable_ports)
        self.menuset_COM_port.addAction(self.actionavailable_ports_2)
        self.menuset_COM_port.addAction(self.actionavailable_ports_3)
        self.menuset_COM_port.addAction(self.actionavailable_ports_4)
        self.menuSettings.addAction(self.menuset_COM_port.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSegment.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Lane No"))
        self.label_2.setText(_translate("MainWindow", "Swimmer"))
        self.label_3.setText(_translate("MainWindow", "   Response"))
        self.label_4.setText(_translate("MainWindow", "   Finished"))
        self.label_5.setText(_translate("MainWindow", "  Position"))
        self.label_6.setText(_translate("MainWindow", "Timer:"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "FINISH"))
        self.label_15.setText(_translate("MainWindow", "      Meter"))
        self.lineEdit_9.setText(_translate("MainWindow", "round"))
        self.pushButton_4.setText(_translate("MainWindow", "SAVE"))
        self.label_7.setText(_translate("MainWindow", "Status"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Swimmer 1"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "Swimmer 2"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "Swimmer 3"))
        self.comboBox_4.setCurrentText(_translate("MainWindow", "Swimmer 4"))
        self.comboBox_5.setCurrentText(_translate("MainWindow", "Swimmer 5"))
        self.comboBox_6.setCurrentText(_translate("MainWindow", "Swimmer 6"))
        self.comboBox_7.setCurrentText(_translate("MainWindow", "Swimmer 7"))
        self.comboBox_8.setCurrentText(_translate("MainWindow", "Swimmer 8"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSegment.setTitle(_translate("MainWindow", "Segment"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuset_COM_port.setTitle(_translate("MainWindow", "set COM port"))
        self.action50m.setText(_translate("MainWindow", "50m"))
        self.action100m_freestyle.setText(_translate("MainWindow", "100m freestyle"))
        self.action100m_backstroke.setText(_translate("MainWindow", "100m backstroke"))
        self.action100m_butterfly.setText(_translate("MainWindow", "100m butterfly"))
        self.action200m_freestyle.setText(_translate("MainWindow", "200m freestyle"))
        self.action200m_backstroke.setText(_translate("MainWindow", "200m backstroke"))
        self.action200m_butterfly.setText(_translate("MainWindow", "200m butterfly"))
        self.actionavailable_ports.setText(_translate("MainWindow", "available ports"))
        self.actionavailable_ports_2.setText(_translate("MainWindow", "available ports"))
        self.actionavailable_ports_3.setText(_translate("MainWindow", "available ports"))
        self.actionavailable_ports_4.setText(_translate("MainWindow", "available ports"))
        self.actionOpen_Database.setText(_translate("MainWindow", "Open Database"))
        self.actionImprovement_Curve.setText(_translate("MainWindow", "Improvement Curve"))
